name          'stevenmerrill-carbon'
version       '0.1.0'
source        'UNKNOWN'
author        'stevenmerrill'
license       'Apache License, Version 2.0'
summary       'Install Carbon from EPEL packages and configure it.'
description   'UNKNOWN'
project_page  'UNKNOWN'

dependency 'puppetlabs/stdlib', '>= 3.2.0'
dependency 'stahnma/epel', '~> 0.0.6'
